### ISSUE TITLE
Compiled Pia Manager.exe

### ISSUE THREAD

**Issue by gerryrin** [erik434/PiaManager#1]
Hello erik434
Any chance that you could upload the compiled exe of Pia Manager? I do not have the c sharp compiler, but I would like to try your Pia Manager with PIA version 75. My HIPS firewall is driving me nuts.  I hope this is the correct way to make such a request.
Thank you

**Comment by erik434** [comment]
No problem! I just built and posted the binary under the releases for this project.

**Comment by gerryrin** [comment]
Hi erik434,
Thank  you for the compiled exe. I have tried it and received and error. I have attached a screen shot.
![2018-01-25_1427](https://user-images.githubusercontent.com/35782265/35416109-d26dcad2-01dc-11e8-9075-4e8ac4589176.png)
