### ISSUE TITLE
PIA Manager.EXE Error Ruby file directory not found

### ISSUE THREAD

**Issue by gerryrin** [erik434/PiaManager#2]
I tried version 1 of your PIA Manager.EXE with PIA v75. I received an error Ruby file directory not found. (screen shot attached) I also took screen shots of the C:\Program Files\pia_manager\bin directory before and after installing PIA Manager.exe and trying to run it. Notice that there are two ruby exes in the bin folder, ruby.exe and rubyw.exe  after installing PIA Manager.exe  I want to thank you again for your work. If there is anything that I can can do, let me know.
![2018-01-25_1427](https://user-images.githubusercontent.com/35782265/35419783-da637702-01ee-11e8-86ea-c755c4f69684.png)
![pia_ bin_ folder_ before_pia manager_install](https://user-images.githubusercontent.com/35782265/35419784-da98972a-01ee-11e8-8859-aa60bc57ed1a.png)
![pia_bin folder_after pia manager_install](https://user-images.githubusercontent.com/35782265/35419785-dac9dd94-01ee-11e8-9058-79426e23845a.png)

**Comment by erik434** [comment]
I think I see the problem - the bin, lib, and src folders from the random temp directory are expected to be in a "pia_ruby_files" subfolder of the main pia_manager directory. So for example you should have C:\Program Files\pia_manager\\**pia_ruby_files**\bin. Please try moving those folders and see if that solves it for you. Sorry the error message isn't very helpful - I haven't spent a lot of time making this project "nice", just good enough to work for me :)

**Comment by gerryrin** [comment]
I am still getting an error. 
Unhandled Exception: System.IO.FileNotFoundException: Could not find pia_manager ruby file
 at PIA_manager.Program.FindPiaFiles()
 at PIA_manager.Program.Main(String[] args)
I have attached a with screen shots of my \pia_manager,\ pia_ruby_files\bin folders and the error message.  My OS is Windows 10 if that makes any difference.  I tried to send these screenshots in a 7z file, but github does not allow it. Thank you again.
![2018-01-26_1235](https://user-images.githubusercontent.com/35782265/35460506-218348ba-0299-11e8-8b5a-a71a5c9979a7.png)
![pia_ruby_files_bin_dir](https://user-images.githubusercontent.com/35782265/35460507-21a0abf8-0299-11e8-91cf-9c0878c4f018.png)
![pia_ruby_files_dir](https://user-images.githubusercontent.com/35782265/35460508-21c08ebe-0299-11e8-823d-f3d4a41f764a.png)
![pia_working_dir](https://user-images.githubusercontent.com/35782265/35460510-21d98e46-0299-11e8-8ba5-ae44cc731c00.png)

**Comment by erik434** [comment]
That error means it can't find the "pia_manager.rb" file inside the src directory. Can you show me the contents of your pia_ruby_files\src folder? Maybe share a screenshot of the bin folder too just in case.

I'm not sure what version of PIA I was using when I developed this. It was the latest version at the time, but it's possible that the v75 you're using is different and I might need to adapt this program slightly to compensate. I'll look into that some more when I get some free time, maybe this weekend.

**Comment by gerryrin** [comment]
I have attached a screen shot of src folder. I think you have found the problem. pia_manager.rb is in src\bin folder. 
I have uninstalled v75 and installed v74. I am willing test with what every versions you want, just so you know which versions it will work with. Thanks again.
![c_program_ files_pia_manager_pia_ruby_files_src_bin](https://user-images.githubusercontent.com/35782265/35462325-4d7d85e6-02a0-11e8-9f4e-3a968d1491da.png)

**Comment by erik434** [comment]
Interesting. Some time between when I wrote this program (to work with PIA v69) and now (PIA v75) they changed where that file lives. I've updated the program so it should work with either location. Can you please verify this works for you? If so, I'll upload it as the v1.1 release: 
[pia_manager.zip](https://github.com/erik434/PiaManager/files/1671008/pia_manager.zip). Please let me know how that does for you. Thanks!
