### ISSUE TITLE
Works Perfect!

### ISSUE THREAD

**Issue by gerryrin** [erik434/PiaManager#3]
pia_manager Version 1.1 works perfect. You are Brilliant! 
Is there a way that I may send you PM?  I would like to pay for a year of PIA service for you. 
Thank You again.

**Comment by erik434** [comment]
Great! I'm happy I could help. I'll get that updated version posted as the next official release.

That's totally not necessary, but it would be appreciated! Feel free to email me at erik.s.bryan@gmail.com. Thank you!

**Comment by erik434** [comment]
Thank you so much! That was very generous. I've pushed the latest source code now as well as the v1.1 binary. You can see the commit here: https://github.com/erik434/PiaManager/commit/20c058f7190c73835894ecf426b3762d4d26e30f
